In [1]:
from IPython.display import HTML
HTML('''
<style>
.prompt {
  display: none;
}
</style>
<script>
  function code_toggle() {
    if (code_shown){
      $('div.input').hide('500');
      $('#toggleButton').val('Show Code')
    } else {
      $('div.input').show('500');
      $('#toggleButton').val('Hide Code')
    }
    code_shown = !code_shown
  }

  $( document ).ready(function(){
    code_shown=false;
    $('div.input').hide()
  });
</script>
<form action="javascript:code_toggle()"><input type="submit" id="toggleButton" value="Show Code"></form>''')

# Data tables


### Below are the data tables we consulted in our analysis. (after data preparation)
[Return to analysis](analysis.ipynb)

In [2]:
import pandas as pd

data_538 = pd.read_csv("./data/hate_crimes.csv")
off_by_bias_motivation = pd.read_csv("./data/table_1_incidents_offenses_victims_and_known_offenders_by_bias_motivation_2016.csv")
off_by_off_type = pd.read_csv("./data/table_2_incidents_offenses_victims_and_known_offenders_by_offense_type_2016.csv")
off_race_by_off_type = pd.read_csv("./data/table_3_offenses_known_offenders_race_and_ethnicity_by_offense_type_2016.csv")
off_type_by_bias_motivation = pd.read_csv("./data/table_4_offenses_offense_type_by_bias_motivation_2016.csv")
off_race_by_bias_motivation = pd.read_csv("./data/table_5_offenses_known_offenders_race_and_ethnicity_by_bias_motivation_2016.csv")
off_by_state = pd.read_csv("./data/table_11_offenses_offense_type_by_participating_state_2016.csv")
locations = pd.read_csv("./data/table_10_incidents_bias_motivation_by_location_2016.csv")

## Hate Crimes data from 538

Shows demographic and hate crime data from each state.

In [3]:
data_538

,code,state,median_household_income,share_unemployed_seasonal,share_population_in_metro_areas,share_population_with_high_school_degree,share_non_citizen,share_white_poverty,share_white_poverty.1,share_white_poverty.2,share_voters_voted_trump,hate_crimes_per_100k_splc,avg_hatecrimes_per_100k_fbi
0,AL,Alabama,42278,0.060,0.64,0.821,0.02,0.12,1.12,2.12,0.63,0.125839,1.806410
1,AK,Alaska,67629,0.064,0.63,0.914,0.04,0.06,1.06,2.06,0.53,0.143740,1.656700
2,AZ,Arizona,49254,0.063,0.90,0.842,0.10,0.09,1.09,2.09,0.50,0.225320,3.413928
3,AR,Arkansas,44922,0.052,0.69,0.824,0.04,0.12,1.12,2.12,0.60,0.069061,0.869209
4,CA,California,60487,0.059,0.97,0.806,0.13,0.09,1.09,2.09,0.33,0.255805,2.397986
5,CO,Colorado,60940,0.040,0.80,0.893,0.06,0.07,1.07,2.07,0.44,0.390523,2.804689
6,CT,Connecticut,70161,0.052,0.94,0.886,0.06,0.06,1.06,2.06,0.41,0.335392,3.772701
7,DE,Delaware,57522,0.049,0.90,0.874,0.05,0.08,1.08,2.08,0.42,0.322754,1.469980
8,DC,District of Columbia,68277,0.067,1.00,0.871,0.11,0.04,1.04,2.04,0.04,1.522302,10.953480
9,FL,Florida,46140,0.052,0.96,0.853,0.09,0.11,1.11,2.11,0.49,0.187521,0.698070
10,GA,Georgia,49555,0.058,0.82,0.839,0.08,0.09,1.09,2.09,0.51,0.120420,0.412012
11,HI,Hawaii,71223,0.034,0.76,0.904,0.08,0.07,1.07,2.07,0.30,NaN,NaN
12,ID,Idaho,53438,0.042,0.70,0.884,0.04,0.11,1.11,2.11,0.59,0.124208,1.891331
13,IL,Illinois,54916,0.054,0.90,0.864,0.07,0.07,1.07,2.07,0.39,0.195345,1.044016
14,IN,Indiana,48060,0.044,0.79,0.866,0.03,0.12,1.12,2.12,0.57,0.247009,1.757357
15,IA,Iowa,57810,0.036,0.60,0.914,0.03,0.09,1.09,2.09,0.52,0.454427,0.561396
16,KS,Kansas,53444,0.044,0.64,0.897,0.04,0.11,1.11,2.11,0.57,0.105152,2.143987
17,KY,Kentucky,42786,0.050,0.56,0.817,0.03,0.17,1.17,2.17,0.63,0.324397,4.207890
18,LA,Louisiana,42406,0.060,0.81,0.822,0.02,0.12,1.12,2.12,0.58,0.109733,1.341170
19,ME,Maine,51710,0.044,0.54,0.902,NaN,0.12,1.12,2.12,0.45,0.615574,2.626611
20,MD,Maryland,76165,0.051,0.97,0.890,0.08,0.06,1.06,2.06,0.35,0.370439,1.324840
21,MA,Massachusetts,63151,0.046,0.97,0.890,0.09,0.08,1.08,2.08,0.34,0.630811,4.801899
22,MI,Michigan,52005,0.050,0.87,0.879,0.04,0.09,1.09,2.09,0.48,0.403779,3.200442
23,MN,Minnesota,67244,0.038,0.75,0.915,0.05,0.05,1.05,2.05,0.45,0.627480,3.612412
24,MS,Mississippi,35521,0.061,0.45,0.804,NaN,0.14,1.14,2.14,0.58,0.067447,0.622746
25,MO,Missouri,56630,0.053,0.78,0.868,0.02,0.07,1.07,2.07,0.57,0.184524,1.908955
26,MT,Montana,51102,0.041,0.34,0.908,0.01,0.10,1.10,2.10,0.57,0.495491,2.954959
27,NE,Nebraska,56870,0.029,0.60,0.898,0.05,0.07,1.07,2.07,0.60,0.159490,2.686248
28,NV,Nevada,49875,0.067,0.87,0.839,0.10,0.08,1.08,2.08,0.46,0.141673,2.113990
29,NH,New Hampshire,73397,0.034,0.63,0.913,0.03,0.06,1.06,2.06,0.47,0.151550,2.105989
30,NJ,New Jersey,65243,0.056,1.00,0.874,0.11,0.07,1.07,2.07,0.42,0.078306,4.413203
31,NM,New Mexico,46686,0.068,0.69,0.828,0.06,0.10,1.10,2.10,0.40,0.294811,1.886435
32,NY,New York,54310,0.051,0.94,0.847,0.10,0.10,1.10,2.10,0.37,0.350620,3.102164
33,NC,North Carolina,46784,0.058,0.76,0.843,0.05,0.10,1.10,2.10,0.51,0.244007,1.262680
34,ND,North Dakota,60730,0.028,0.50,0.901,0.03,0.09,1.09,2.09,0.64,NaN,4.741070
35,OH,Ohio,49644,0.045,0.75,0.876,0.03,0.10,1.10,2.10,0.52,0.190714,3.240420
36,OK,Oklahoma,47199,0.044,0.59,0.856,0.04,0.10,1.10,2.10,0.65,0.133629,1.081672
37,OR,Oregon,58875,0.062,0.87,0.891,0.07,0.10,1.10,2.10,0.41,0.832850,3.394886
38,PA,Pennsylvania,55173,0.053,0.87,0.879,0.03,0.09,1.09,2.09,0.49,0.285101,0.430928
39,RI,Rhode Island,58633,0.054,1.00,0.847,0.08,0.08,1.08,2.08,0.40,0.095402,1.282572
40,SC,South Carolina,44929,0.057,0.79,0.836,0.03,0.09,1.09,2.09,0.55,0.209894,1.937083
41,SD,South Dakota,53053,0.035,0.51,0.899,NaN,0.08,1.08,2.08,0.62,NaN,3.301737
42,TN,Tennessee,43716,0.057,0.82,0.831,0.04,0.13,1.13,2.13,0.61,0.199938,3.136051
43,TX,Texas,53875,0.042,0.92,0.799,0.11,0.08,1.08,2.08,0.53,0.213584,0.752768
44,UT,Utah,63383,0.036,0.82,0.904,0.04,0.08,1.08,2.08,0.47,0.136547,2.384065
45,VT,Vermont,60708,0.037,0.35,0.910,0.01,0.10,1.10,2.10,0.33,0.324149,1.903081
46,VA,Virginia,66155,0.043,0.89,0.866,0.06,0.07,1.07,2.07,0.45,0.363249,1.724755
47,WA,Washington,59068,0.052,0.86,0.897,0.08,0.09,1.09,2.09,0.38,0.677488,3.817740
48,WV,West Virginia,39552,0.073,0.55,0.828,0.01,0.14,1.14,2.14,0.69,0.328677,2.037054
49,WI,Wisconsin,58080,0.043,0.69,0.898,0.03,0.09,1.09,2.09,0.48,0.226197,1.121945
50,WY,Wyoming,55690,0.040,0.31,0.918,0.02,0.09,1.09,2.09,0.70,NaN,0.266941

## Incidents, Offenses, Victims, and Known Offenders by Offense Type

FBI data

In [12]:
off_by_bias_motivation[['Bias motivation', 'Incidents', 'Offenses', 'Victims', 'Known offenders']][0:34]

,Bias motivation,Incidents,Offenses,Victims,Known offenders
0,Anti-White,720,876,909,831
1,Anti-Black or African American,1739,2122,2220,1588
2,Anti-American Indian or Alaska Native,154,161,169,118
3,Anti-Asian,113,131,137,123
4,Anti-Native Hawaiian or Other Pacific Islander,9,9,9,8
5,"Anti-Multiple Races, Group",136,178,190,104
6,Anti-Arab,51,56,57,60
7,Anti-Hispanic or Latino,344,449,483,380
8,Anti-Other Race/Ethnicity/Ancestry,223,247,252,171
9,Anti-Jewish,684,834,862,421
10,Anti-Catholic,62,63,65,45
11,Anti-Protestant,15,20,22,12
12,Anti-Islamic (Muslim),307,381,388,243
13,Anti-Other Religion,74,90,91,53
14,"Anti-Multiple Religions, Group",34,48,48,20
15,Anti-Mormon,7,8,8,3
16,Anti-Jehovah's Witness,2,3,3,1
17,"Anti-Eastern Orthodox (Russian, Greek, Other)",28,28,30,23
18,Anti-Other Christian,36,37,39,13
19,Anti-Buddhist,1,1,1,0
20,Anti-Hindu,10,12,12,11
21,Anti-Sikh,7,7,8,10
22,Anti-Atheism/Agnosticism/etc.,6,6,7,4
23,Anti-Gay (Male),675,765,787,806
24,Anti-Lesbian,124,141,147,127
25,"Anti-Lesbian, Gay, Bisexual, or Transgender (M...",234,262,271,254
26,Anti-Heterosexual,20,23,23,13
27,Anti-Bisexual,23,27,27,25
28,Anti-Physical Disability,26,29,30,29
29,Anti-Mental Disability,44,47,47,38
30,Anti-Male,7,10,10,7
31,Anti-Female,24,26,26,21
32,Anti-Transgender,105,111,111,149
33,Anti-Gender Non-Conforming,19,19,20,16

## Offenses by offense type

In [16]:
off_by_off_type[['offense_type', 'Incidents', 'Offenses', 'Victims', 'Known offenders']][0:15]

,offense_type,Incidents,Offenses,Victims,Known offenders
0,Murder and nonnegligent manslaughter,5,9,9,9
1,Rape (revised definition),24,24,24,29
2,Rape (legacy definition),0,0,0,0
3,Aggravated assault,684,873,873,1031
4,Simple assault,1458,1687,1687,1857
5,Intimidation,1577,2109,2109,1409
6,Robbery,134,134,163,249
7,Burglary,123,123,138,87
8,Larceny-theft,231,231,253,173
9,Motor vehicle theft,20,20,21,14
10,Arson,39,39,51,33
11,Destruction/damage/vandalism,1913,1913,2122,1015
12,Other crimes against persons,17,18,18,18
13,Other crimes against property,59,59,65,47
14,Crimes against society,82,82,82,97

## Known offender by offense type

In [14]:
off_race_by_off_type[0:15]

,Offense type,Total,White,Black or African American,American Indian or Alaska Native,Asian,Native Hawaiian or Other Pacific Islander,Group of multiple races,Unknown race,Hispanic or Latino,Not Hispanic or Latino,Group of multiple ethnicities,Unknown ethnicity,Unknown offender
0,Murder and nonnegligent manslaughter,9,4,5,0,0,0,0,0,0,1,0,3,0
1,Rape (revised definition),24,9,6,2,0,0,0,3,2,2,1,14,4
2,Rape (legacy definition),0,0,0,0,0,0,0,0,0,0,0,0,0
3,Aggravated assault,873,395,268,9,7,1,63,56,69,179,9,313,74
4,Simple assault,1687,764,513,17,9,3,93,184,90,377,14,654,104
5,Intimidation,2109,1015,322,7,19,0,43,262,52,288,4,893,441
6,Other crimes against persons,18,10,3,0,0,0,0,0,1,9,0,3,5
7,Robbery,134,25,67,3,0,0,13,11,10,30,1,47,15
8,Burglary,123,33,11,1,1,0,3,18,2,12,2,35,56
9,Larceny-theft,231,69,33,1,1,0,2,33,1,21,1,101,92
10,Motor vehicle theft,20,3,3,0,0,0,1,4,0,0,0,11,9
11,Arson,39,13,5,0,0,0,2,4,3,3,1,7,15
12,Destruction/damage/vandalism,1913,267,69,7,7,3,24,422,23,85,3,329,1114
13,Other crimes against property,59,19,6,0,0,0,0,12,1,2,0,34,22
14,Crimes against society,82,54,20,2,1,0,1,1,0,17,2,60,3

## Offense type by bias motivation

In [17]:
off_type_by_bias_motivation[0:35]

,Bias motivation,Total,Murder and nonnegligent manslaughter,Rape(revised definition1),Aggravated assault,Simple assault,Intimidation,Robbery,Burglary,Larceny-theft,Motor vehicle theft,Arson,Destruction/damage/vandalism,Crimes,Other
0,Anti-White,876,5,5,120,241,188,30,22,78,6,2,122,31,26
1,Anti-Black or African American,2122,2,2,273,455,782,14,17,14,2,7,537,10,7
2,Anti-American Indian or Alaska Native,161,0,1,8,17,36,0,18,31,4,0,29,5,12
3,Anti-Asian,131,0,0,15,40,45,2,4,5,0,0,18,2,0
4,Anti-Native Hawaiian or Other Pacific Islander,9,0,0,0,4,3,0,0,0,0,0,2,0,0
5,"Anti-Multiple Races, Group",178,0,0,17,36,49,4,5,0,1,2,62,0,2
6,Anti-Arab,56,0,0,8,16,17,1,0,0,0,1,13,0,0
7,Anti-Hispanic or Latino,449,0,1,91,129,140,19,2,5,0,0,57,4,1
8,Anti-Other Race/Ethnicity/Ancestry,247,0,1,16,64,60,1,7,16,1,1,76,1,3
9,Anti-Jewish,834,0,0,12,61,238,3,9,15,1,4,489,1,1
10,Anti-Catholic,63,0,0,1,5,6,0,3,10,1,1,31,4,1
11,Anti-Protestant,20,0,0,1,3,1,0,1,4,0,1,8,1,0
12,Anti-Islamic (Muslim),381,0,0,52,75,144,4,2,3,0,5,92,4,0
13,Anti-Other Religion,90,0,0,13,10,8,1,6,1,0,0,49,1,1
14,"Anti-Multiple Religions, Group",48,0,0,2,4,21,1,1,1,1,2,15,0,0
15,Anti-Mormon,8,0,0,0,0,2,0,0,1,0,1,2,2,0
16,Anti-Jehovah's Witness,3,0,0,0,0,2,0,0,1,0,0,0,0,0
17,"Anti-Eastern Orthodox (Russian, Greek, Other)",28,0,0,1,4,2,0,3,8,1,0,5,2,2
18,Anti-Other Christian,37,0,0,1,3,2,1,3,2,0,3,22,0,0
19,Anti-Buddhist,1,0,0,0,0,0,0,0,0,0,0,1,0,0
20,Anti-Hindu,12,0,0,1,2,6,0,0,0,0,0,2,1,0
21,Anti-Sikh,7,0,0,1,1,1,0,1,0,0,0,2,0,1
22,Anti-Atheism/Agnosticism/etc.,6,0,1,0,0,0,0,0,1,0,1,2,0,1
23,Anti-Gay (Male),765,1,1,126,281,183,28,6,6,0,1,126,3,3
24,Anti-Lesbian,141,0,4,23,46,37,0,2,3,0,2,23,0,1
25,"Anti-Lesbian, Gay, Bisexual, or Transgender (M...",262,0,4,45,71,59,10,1,1,1,3,64,1,2
26,Anti-Heterosexual,23,0,0,1,2,7,0,0,5,0,0,6,2,0
27,Anti-Bisexual,27,0,0,2,14,3,0,1,2,1,0,2,0,2
28,Anti-Physical Disability,29,0,0,2,15,4,0,2,2,0,0,1,1,2
29,Anti-Mental Disability,47,0,2,3,18,5,1,1,6,0,0,5,4,2
30,Anti-Male,10,1,0,0,7,1,0,1,0,0,0,0,0,0
31,Anti-Female,26,0,0,6,4,6,0,2,0,0,0,7,0,1
32,Anti-Transgender,111,0,1,24,47,14,11,1,2,0,1,5,0,5
33,Anti-Gender Non-Conforming,19,0,0,1,2,2,0,1,4,0,0,7,2,0
34,Multiple-Bias Incidents,94,0,1,7,10,35,3,1,4,0,1,31,0,1

## Offender race by bias motivation

In [22]:
off_race_by_bias_motivation[['White', 'Black or African American', 'American Indian or Alaska Native', 'Asian', 'Native Hawaiian or Other Pacific Islander', 'Group of multiple races', 'Unknown race', 'Unknown offender']][0:35]

,White,Black or African American,American Indian or Alaska Native,Asian,Native Hawaiian or Other Pacific Islander,Group of multiple races,Unknown race,Unknown offender
0,133,452,20,6,0,27,80,158
1,1142,80,9,17,1,88,202,583
2,56,28,2,0,0,3,14,58
3,65,20,2,6,0,5,9,24
4,4,4,0,0,0,0,0,1
5,54,33,0,1,0,9,17,64
6,32,6,0,1,0,3,6,8
7,228,114,2,0,1,12,24,68
8,61,44,2,1,0,3,46,90
9,156,34,4,0,0,12,300,328
10,9,3,0,2,0,3,22,24
11,11,2,0,0,0,0,3,4
12,135,49,1,2,0,9,66,119
13,20,20,0,1,2,1,7,39
14,20,1,0,0,0,4,4,19
15,2,2,0,0,0,0,0,4
16,2,0,0,0,0,0,0,1
17,15,3,0,0,0,0,1,9
18,4,2,0,0,0,1,6,24
19,0,0,0,0,0,0,0,1
20,9,0,0,0,0,1,0,2
21,4,1,0,0,0,1,1,0
22,2,1,0,0,0,0,0,3
23,257,223,2,1,2,33,102,145
24,51,37,0,0,0,3,14,36
25,86,53,4,3,1,12,37,66
26,12,1,0,2,0,1,0,7
27,8,12,0,0,0,0,3,4
28,14,8,0,1,0,1,2,3
29,21,8,1,0,0,0,4,13
30,10,0,0,0,0,0,0,0
31,8,9,0,0,0,1,4,4
32,27,54,0,0,0,9,14,7
33,3,3,0,1,0,0,5,7
34,19,24,0,0,0,3,17,31

## Offender ethnicity by bias motivation

In [21]:
off_race_by_bias_motivation[['Hispanic or Latino', 'Not Hispanic or Latino', 'Group of multiple ethnicities', 'Unknown ethnicity', 'Unknown offender']][0:35]

,Hispanic or Latino,Not Hispanic or Latino,Group of multiple ethnicities,Unknown ethnicity
0,22,169,9,393
1,82,267,5,808
2,1,3,0,92
3,6,28,3,40
4,0,1,0,3
5,2,31,1,50
6,4,16,0,14
7,15,112,2,150
8,3,35,2,68
9,9,16,4,152
10,4,3,0,14
11,0,8,0,6
12,5,40,2,121
13,2,16,2,18
14,0,4,0,21
15,0,4,0,0
16,0,0,0,0
17,0,4,0,15
18,3,1,0,5
19,0,0,0,0
20,0,2,0,5
21,0,2,1,4
22,0,0,0,3
23,63,126,6,209
24,6,24,0,34
25,10,20,1,140
26,1,1,0,9
27,0,6,0,14
28,0,7,0,14
29,2,7,0,25
30,0,2,0,8
31,0,6,0,9
32,12,33,0,30
33,0,4,0,2
34,2,28,0,28

## Offense type by state

In [23]:
off_by_state[1::]

,state,total,Murder and nonnegligent manslaughter,Rape (revised definition1),Aggravated assault,Simple assault,Intimidation,Robbery,Burglary,Larceny-theft,Motor vehicle theft,Arson,Destruction/damage/vandalism,Crimes against society,Other
1,Alabama,17,0,0.0,0,2,11,0,0,2,0,0,2,0,0
2,Alaska,13,0,0.0,1,6,1,1,0,0,0,1,3,0,0
3,Arizona,291,0,0.0,41,65,112,6,1,4,0,0,62,0,0
4,Arkansas,15,0,0.0,1,5,2,0,1,1,0,1,3,1,0
5,California,1142,0,1.0,191,240,308,31,14,6,2,12,337,0,0
6,Colorado,126,0,1.0,15,25,39,4,1,1,0,1,39,0,0
7,Connecticut,124,0,0.0,12,18,40,1,1,7,0,0,39,5,1
8,Delaware,19,0,0.0,1,7,5,0,0,0,0,0,5,0,1
9,District of Columbia,127,0,0.0,17,62,23,6,0,2,0,0,17,0,0
10,Florida,110,0,0.0,28,28,18,4,0,0,0,1,31,0,0
11,Georgia,46,0,NaN,6,16,12,1,1,0,0,0,10,0,0
12,Idaho,35,1,0.0,7,9,5,0,0,0,0,0,13,0,0
13,Illinois,122,0,1.0,23,32,31,1,0,1,0,1,32,0,0
14,Indiana,163,3,1.0,4,24,101,1,0,0,0,0,23,5,1
15,Iowa,21,0,0.0,4,2,8,0,0,0,0,1,5,1,0
16,Kansas,70,0,0.0,16,11,26,0,2,4,0,0,9,0,2
17,Kentucky,241,0,0.0,15,39,76,4,11,20,4,2,61,2,7
18,Louisiana,33,0,0.0,5,10,7,0,2,3,0,0,4,2,0
19,Maine,45,0,0.0,1,6,23,0,0,1,0,0,14,0,0
20,Maryland,40,0,0.0,11,11,0,1,0,0,0,0,17,0,0
21,Massachusetts,444,0,1.0,54,84,139,2,4,14,0,3,136,2,5
22,Michigan,459,0,3.0,62,96,179,2,6,10,1,1,75,16,8
23,Minnesota,165,0,0.0,28,52,47,4,0,1,0,1,32,0,0
24,Mississippi,10,0,0.0,0,3,0,0,2,2,0,0,3,0,0
25,Missouri,114,0,1.0,27,32,20,7,2,1,2,1,20,1,0
26,Montana,20,0,1.0,1,2,3,0,2,4,1,0,4,1,1
27,Nebraska,35,0,1.0,4,14,4,1,0,0,0,0,8,2,1
28,Nevada,49,0,1.0,13,18,3,3,1,0,1,0,9,0,0
29,New Hampshire,40,0,0.0,1,5,24,0,0,0,0,0,10,0,0
30,New Jersey,308,0,0.0,2,12,179,3,2,2,0,0,108,0,0
31,New Mexico,36,0,0.0,3,13,11,1,2,0,0,0,6,0,0
32,New York,598,0,1.0,61,209,0,9,11,11,0,7,289,0,0
33,North Carolina,208,0,0.0,27,47,70,5,3,5,0,1,50,0,0
34,North Dakota,8,0,0.0,1,4,3,0,0,0,0,0,0,0,0
35,Ohio,508,0,0.0,22,68,224,6,22,58,5,0,84,3,16
36,Oklahoma,35,0,2.0,2,7,15,2,0,0,0,1,5,0,1
37,Oregon,122,0,1.0,18,20,33,1,2,1,0,0,43,2,1
38,Pennsylvania,67,0,0.0,3,24,25,0,1,2,0,2,10,0,0
39,Rhode Island,13,0,0.0,0,4,0,1,0,0,0,0,7,1,0
40,South Carolina,23,0,0.0,4,5,4,0,0,2,0,0,8,0,0
41,South Dakota,21,0,0.0,1,9,2,0,1,1,0,0,3,4,0
42,Tennessee,190,0,0.0,18,62,44,2,3,9,0,0,35,14,3
43,Texas,224,5,0.0,42,57,53,9,3,8,0,0,42,0,5
44,Utah,72,0,2.0,2,22,2,1,3,6,0,0,18,13,3
45,Vermont,26,0,0.0,1,8,1,0,1,4,0,0,11,0,0
46,Virginia,150,0,2.0,10,52,31,2,1,4,0,1,42,1,4
47,Washington,482,0,2.0,52,111,133,11,13,22,4,1,113,5,15
48,West Virginia,48,0,2.0,10,16,2,1,2,9,0,0,3,1,2
49,Wisconsin,42,0,0.0,4,10,10,0,2,3,0,0,13,0,0
50,Wyoming,4,0,0.0,1,3,0,0,0,0,0,0,0,0,0

## Bias motivation by location type

In [24]:
locations[1::]

,Location,Total incidents,Race/Ethnicity/Ancestry,Religion,Sexual orientation,Disability,Gender,Gender Identity,Multiple-bias incidents,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
1,Abandoned/condemned structure,5,2,3,0,0,0,0,0,NaN,NaN,NaN,NaN
2,Air/bus/train terminal,94,60,11,16,2,0,2,3,NaN,NaN,NaN,NaN
3,Amusement park,1,0,0,1,0,0,0,0,NaN,NaN,NaN,NaN
4,Arena/stadium/fairgrounds/coliseum,6,4,1,1,0,0,0,0,NaN,NaN,NaN,
5,ATM separate from bank,1,1,0,0,0,0,0,0,NaN,NaN,NaN,NaN
6,Auto dealership new/used,6,6,0,0,0,0,0,0,NaN,NaN,NaN,NaN
7,Bank/savings and loan,20,11,6,1,0,1,1,0,NaN,NaN,NaN,NaN
8,Bar/nightclub,96,49,3,43,0,0,0,1,NaN,NaN,NaN,NaN
9,Camp/campground,3,2,0,1,0,0,0,0,NaN,NaN,NaN,NaN
10,Church/synagogue/temple/mosque,241,36,194,8,0,0,0,3,NaN,NaN,NaN,NaN
11,Commercial office building,117,63,29,20,1,0,3,1,NaN,NaN,NaN,NaN
12,Community center,11,5,4,2,0,0,0,0,NaN,NaN,NaN,NaN
13,Construction site,19,12,7,0,0,0,0,0,NaN,NaN,NaN,NaN
14,Convenience store,88,57,16,11,0,1,3,0,NaN,NaN,NaN,NaN
15,Cyberspace,4,3,0,1,0,0,0,0,NaN,NaN,NaN,NaN
16,Daycare facility,2,2,0,0,0,0,0,0,NaN,NaN,NaN,NaN
17,Department/discount store,72,45,11,13,2,0,1,0,NaN,NaN,NaN,NaN
18,Dock/wharf/freight/modal terminal,3,2,1,0,0,0,0,0,NaN,NaN,NaN,NaN
19,Drug store/doctor's office/hospital,64,49,11,2,2,0,0,0,NaN,NaN,NaN,NaN
20,Farm facility,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN
21,Field/woods,31,19,7,2,0,0,3,0,NaN,NaN,NaN,NaN
22,Gambling facility/casino/race track,3,3,0,0,0,0,0,0,NaN,NaN,NaN,NaN
23,Government/public building,111,73,24,10,1,2,0,1,NaN,NaN,NaN,NaN
24,Grocery/supermarket,62,46,7,8,0,0,1,0,NaN,NaN,NaN,NaN
25,Highway/road/alley/street/sidewalk,1128,718,117,241,7,1,35,9,NaN,NaN,NaN,NaN
26,Hotel/motel/etc.,44,32,3,8,0,0,1,0,NaN,NaN,NaN,NaN
27,Industrial site,12,10,1,1,0,0,0,0,NaN,NaN,NaN,NaN
28,Jail/prison/penitentiary/corrections facility,61,42,3,13,1,1,0,1,NaN,NaN,NaN,NaN
29,Lake/waterway/beach,6,2,0,4,0,0,0,0,NaN,NaN,NaN,NaN
30,Liquor store,15,12,2,1,0,0,0,0,NaN,NaN,NaN,NaN
31,Military installation,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN
32,Park/playground,98,66,13,12,2,1,2,2,NaN,NaN,NaN,NaN
33,Parking/drop lot/garage,351,222,50,68,3,0,5,3,NaN,NaN,NaN,NaN
34,Rental storage facility,9,5,3,0,0,0,1,0,NaN,NaN,NaN,NaN
35,Residence/home,1670,1008,249,327,32,11,24,19,NaN,NaN,NaN,NaN
36,Rest area,4,3,0,1,0,0,0,0,NaN,NaN,NaN,NaN
37,Restaurant,143,92,14,29,3,2,3,0,NaN,NaN,NaN,NaN
38,School/college,146,67,52,24,0,1,0,2,NaN,NaN,NaN,NaN
39,college/university,210,107,61,36,1,0,5,0,NaN,NaN,NaN,NaN
40,elementary/secondary school,248,155,48,29,6,1,2,7,NaN,NaN,NaN,NaN
41,Service/gas station,72,55,8,6,0,0,3,0,NaN,NaN,NaN,NaN
42,Shelter: mission/homeless,16,10,2,2,0,0,2,0,NaN,NaN,NaN,NaN
43,Shopping mall,8,6,2,0,0,0,0,0,NaN,NaN,NaN,NaN
44,"Specialty store (TV, fur, etc.)",39,28,9,2,0,0,0,0,NaN,NaN,NaN,NaN
45,Other/unknown,777,297,301,132,7,8,27,5,NaN,NaN,NaN,NaN
46,Multiple locations,4,2,0,0,0,1,0,1,NaN,NaN,NaN,NaN